name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Bun for installation, building, and testing
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Setup Node.js only for npm publishing with OIDC until Bun adds support for it - https://github.com/oven-sh/bun/issues/15601
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      # Use Bun for everything except publishing
      - run: bun install
      - run: bun run build
      - run: bun test

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
      # Use npm only for publishing with OIDC support
      - run: npm publish --access public --provenance
